package com.example.lab5mod4.secret

object TmdbApiKeys {
    const val API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkNzNhZmVjNjgxNmEyOTcxMTA5NTExOTgwNWUyMmM4MiIsInN1YiI6IjY0ZjYxZTIzMTIxOTdlMDBmZWE5NmE3NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.FviUjVI5N-xoqCPpYZy9Fd56KLGwHU0NkMIGefLnSlY"
}